### ISSUE TITLE
thonny backend

### ISSUE THREAD

**Issue by mohannugawela** [mohannugawela/mohannugawela.github.io#1]
thonny 3.314 running on Linux mint 21.1 vera.(64 bit) using Python 3.10.6(64bit) TK 8.6.12
ERROR   thonny.plugins.micropython.backend: Crash in backend
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/backend.py", line 136, in __init__
    self._prepare_after_soft_reboot(clean)
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/backend.py", line 167, in _prepare_after_soft_reboot
    self._update_cwd()
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/bare_metal_backend.py", line 402, in _update_cwd
    super()._update_cwd()
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/backend.py", line 493, in _update_cwd
    self._cwd = self._evaluate("__thonny_helper.getcwd()")
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/backend.py", line 611, in _evaluate
    raise ManagementError(script, out, err)
thonny.plugins.micropython.backend.ManagementError: Problem with a management command

SCRIPT:
__thonny_helper.print_mgmt_value(__thonny_helper.getcwd())
STDOUT:
STDERR:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 44, in getcwd
AttributeError: no such attribute

Backend terminated or disconnected. Use 'Stop/Restart' to restart.

**Comment by mohannugawela** [comment]
[Apologies for incomplete info. Esp8266MOD connected via USB and CH340 .
